name: Deploy Godot to itch.io

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-web:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Godot exportieren
        id: export
        uses: firebelley/godot-export@v6.0.0
        with:
          relative_project_path: ./
          archive_output: false
          presets_to_export: "Web"
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.6.2-stable/Godot_v4.6.2-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.6.2-stable/Godot_v4.6.2-stable_export_templates.tpz

      - name: Butler installieren
        uses: remarkablegames/setup-butler@v1

      - name: Nach itch.io hochladen
        run: |
          ls -R "${{ steps.export.outputs.build_directory }}"
          butler push "${{ steps.export.outputs.build_directory }}" kr0n3rd/astroids:web --userversion "${GITHUB_SHA::7}"
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}